import unittest
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

class flyboard(unittest.TestCase):

   def setUp(self):
       self.driver = webdriver.Chrome()

   def test_buyProducts(self):
       user = "instructor"
       pwd = "instructor1a"
       driver = self.driver
       driver.maximize_window()
       driver.get("http://abrarblog.pythonanywhere.com")
       time.sleep(1)
       elem= driver.find_element_by_xpath("//*[@id='navbarNavDropdown']/ul/ul").click()
       elem = driver.find_element_by_css_selector("#content > div.wrapper > form > input:nth-child(3)")
       elem.send_keys(user)
       elem = driver.find_element_by_css_selector("#content > div.wrapper > form > input:nth-child(4)")
       elem.send_keys(pwd)
       elem= driver.find_element_by_css_selector("#content > div.wrapper > form > input.btn.btn-lg.btn-primary.btn-block").click()
       #time.sleep(1)
       elem = driver.find_element_by_link_text("SKATEBOARDS").click()
       #time.sleep(1)
       elem=driver.find_element_by_css_selector("#main > div > div:nth-child(1) > a > img").click()
       #time.sleep(1)
       elem=driver.find_element_by_css_selector("#content > div > div > div:nth-child(2) > form > input[type='submit']:nth-child(5)").click()
       #time.sleep(1)
       elem=driver.find_element_by_css_selector("#content > div > p > a:nth-child(1)").click()
       #time.sleep(1)
       elem = driver.find_element_by_link_text("BLOWOUT DEALS").click()
       #time.sleep(2)
       elem= driver.find_element_by_css_selector("#main > div > div:nth-child(1) > a > img").click()
       #time.sleep(2)
       elem= driver.find_element_by_css_selector("#content > div > div > div:nth-child(2) > form > input[type='submit']:nth-child(5)").click()
       #time.sleep(2)
       elem = driver.find_element_by_css_selector("#id_quantity")
       print(elem.text)
       elem.send_keys(5)
       #time.sleep(2)
       elem=driver.find_element_by_xpath("//*[@id='content']/div/table/tbody/tr[1]/td[3]/form/input[2]").click()
       #time.sleep(1)
       elem = driver.find_element_by_xpath("//*[@id='content']/div/p/a[2]").click()
       #time.sleep(4)
       elem = driver.find_element_by_id("id_first_name")
       elem.send_keys("Loren")
       #time.sleep(1)
       elem = driver.find_element_by_id("id_last_name")
       elem.send_keys("Herdon")
       #time.sleep(1)
       elem = driver.find_element_by_id("id_email")
       elem.send_keys("Loren@gmail.com")
       #time.sleep(2)
       elem = driver.find_element_by_id("id_address")
       elem.send_keys("1806 Frederick Street Citrus Heights, CA 95610")
       #time.sleep(2)
       elem = driver.find_element_by_id("id_postal_code")
       elem.send_keys("95610")
       #time.sleep(2)
       elem = driver.find_element_by_id("id_city")
       elem.send_keys("San Jose")
       #time.sleep(2)
       elem = driver.find_element_by_xpath("//*[@id='content']/form/p[7]/input").click()
       elem = driver.find_element_by_css_selector("#content > form > input[type='image']:nth-child(12)").click()
       time.sleep(4)
       elem = driver.find_element_by_css_selector("#checkoutAsAGuestBtn").click()
       time.sleep(10)
       elem = driver.find_element_by_id("cc")
       elem.send_keys(4929287837496804)
       elem = driver.find_element_by_xpath("//*[@id='expiry_value']")
       elem.send_keys("09/22")
       elem = driver.find_element_by_id("cvv")
       elem.send_keys(218)
       elem = driver.find_element_by_xpath("//*[@id='firstName']")
       elem.send_keys("Loren")
       elem = driver.find_element_by_xpath("//*[@id='lastName']")
       elem.send_keys("Herdon")
       elem = driver.find_element_by_xpath("//*[@id='billingLine1']")
       elem.send_keys("1806 Frederick Street")
       elem = driver.find_element_by_xpath("//*[@id='billingLine2']")
       elem.send_keys("Citrus Heights")
       elem = driver.find_element_by_xpath("//*[@id='billingCity']")
       elem.send_keys("Citrus Heights")
       elem = driver.find_element_by_xpath("//*[@id='billingState']")
       elem.send_keys("NE")
       elem = driver.find_element_by_xpath("//*[@id='billingPostalCode']")
       elem.send_keys(95610)
       elem = driver.find_element_by_xpath("//*[@id='telephone']")
       elem.send_keys(5312037029)
       elem = driver.find_element_by_xpath("//*[@id='email']")
       elem.send_keys("LorenWHerdon@rhyta.com")
       elem = driver.find_element_by_xpath("//*[@id='guestSubmit']").click()
       time.sleep(15)
       elem = driver.find_element_by_id("notNow").click()
       time.sleep(5)
       elem = driver.find_element_by_css_selector("#merchantReturnBtn")
       elem.text
       time.sleep(5)


   def tearDown(self):
       self.driver.close()

if __name__ == "__main__":
   unittest.main()
